### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by SivanMehta** [SivanMehta/golang-react#1]
- [x] 1. Get server side rendering working
- [ ] 2. Get basic stateful react app running
- [x] 3. Get basic http golang app working
- [ ] 4. Put them together (hard part)
  - "compile" client-side by getting server-side render and dumping it to an HTML
  - server side now just uses that as part of a template to serve rest of assets.

**Comment by SivanMehta** [comment]
1) was done by https://github.com/SivanMehta/golang-react/commit/c60ae402956abfbcdba216cdf2ab355363a36a89

**Comment by SivanMehta** [comment]
3. was done by https://github.com/SivanMehta/golang-react/commit/eb2fc89b868149980cf5aee3506cab94f3ffe960
